name: Angular CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up node environment
      uses: actions/setup-node@v2
      with:
        node-version: 22.12.0

    - name: Install dependencies
      run: npm ci

    - name: Linting
      run: npm run lint

    - name: Run tests
      run: npm run ci-test

    - name: Build Angular application
      run: npm run build --prod
    
    - name: Deploy the application
      run: echo Deploying...