name: Issue workflow
on:
 issues: 
  types: [opened, edited, deleted]
jobs:
 issuereport: 
  runs-on: ubuntu-latest

  steps:
   - name: Display Issue context 
     run: echo "${{ toJSON(github.event) }}"